### ISSUE TITLE
Trying to install 3 instances of infinitude

### ISSUE THREAD

**Issue by ccc11223** [nebulous/infinitude#178]
I have 3 carrier HVAC units in my house so I need to run 3 instances of infinitude to point one of them to each. I know that I need to change the port infinitude is running on so they can each be unique but don't fully know how to accomplish that. 

I can run the available image off dockerhub without any issues and connect 1 of my thermostats. I'm trying to get the other two instances up and running using docker compose (I'm running this all on an Unraid server if that is useful). I copied the dockercompose file and changed the line "ports: -3000:3000" to ports: -3001:3001". I then save the file and click on compose up and get the following warning "infinitude Published ports are discarded when using host network mode" the new container seems to occupy both 3000 and 3001 however I can't access infinitude at port 3001. 

I'm sure I'm missing a few steps and am hoping someone can point me in the right direction

**Comment by nebulous** [comment]
Every installation is a bit different, so the compose file references a few options, some of them commented out, as hints for how one might go about things. This is well-intentioned, but may be _completely confusing_ - so apologies if it is 😄 

I think the simplest thing to do in your case to keep everything partitioned in a way that's easy to reason about would be to make a separate folder for each instance of infinitude you plan to run. Inside which you can have a simplified docker-compose.yaml file that looks like the following:

```yaml
version: "2.1"

services:
  infinitude:
    container_name: infinitude_ONE
    hostname: infinitude_ONE
    image: nebulous/infinitude:latest
    ports:
      - "4000:3000"
    volumes:
      - ./state:/infinitude/state
    restart: always
```


replace `ONE` above with a meaningful string for each system - say `guesthouse` or whatever.
then see the `ports:` section. The first number is the port that you'd like to access Infinitude on, and the second is the port running _inside_ the container, so can always be `3000`
